# Global Project Platform
platform :ios, "7.0"

target "WaterReporter" do
	pod 'AFNetworking'
	pod 'MagicalRecord'
	pod 'MBXMapKit'
    pod 'UIImage-ResizeMagick'
end

target "WaterReporterTests" do

end

