# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"
source 'https://github.com/CocoaPods/Specs.git'

target "Water-Reporter" do
  pod 'AFNetworking'
  pod 'MagicalRecord'
    pod 'MBXMapKit', '0.2.1'
    pod 'UIImage-ResizeMagick'
    pod 'MBProgressHUD'
end

target "Water-ReporterTests" do

end

