source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'Water-Reporter' do
  pod 'Alamofire', '3.5'
  pod 'SwiftyJSON', '2.4'
  pod 'Kingfisher', '2.6.1'
  pod 'ActiveLabel', '0.6.2'
  pod 'FacebookCore', '0.1.1'
  pod 'FacebookShare', '0.1.1'
  pod 'FacebookLogin', '0.1.1'
end
